QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = 'Civilian', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Freelancer', payment = 10 } } },
	bus = { label = 'Bus', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	judge = { 
		label = 'Honorary', 
		defaultDuty = true, 
		offDutyPay = false, 
		grades = { 
			['0'] = { name = 'Judge', isboss = true, payment = 2000 } 
		}, 
	},
	lawyer = { 
		label = 'Law Firm', 
		defaultDuty = true, 
		offDutyPay = false, 
		grades = { 
			['0'] = { name = 'lawyer', payment = 1000 },
			['1'] = { name = 'attonery', payment = 1500 },
			['2'] = { name = 'District Attonery', payment = 2000 },
			['3'] = { name = 'Public Defender', payment = 2500 },
			['4'] = { name = 'Law firm Director', isboss = true, payment = 3000 } 
		}, 
	},
	reporter = { label = 'Reporter', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Journalist', payment = 50 } } },
	trucker = { label = 'Trucker', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	tow = { label = 'Towing', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	garbage = { label = 'Garbage', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Collector', payment = 50 } } },
	vineyard = { label = 'Vineyard', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Picker', payment = 50 } } },
	hotdog = { label = 'Hotdog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sales', payment = 50 } } },

	police = {
		label = 'Lspd',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 4000 },
			['1'] = { name = 'Officer I', payment = 4300 },
			['2'] = { name = 'Officer II', payment = 4500 },
			['3'] = { name = 'Officer III', payment = 4700 },
			['4'] = { name = 'Corporal', payment = 4900 },
			['5'] = { name = 'Sergeant', payment = 5100 },
			['6'] = { name = 'Lieutenant', payment = 5300 },
			['7'] = { name = 'Captain', payment = 5500 },
			['8'] = { name = 'Major', payment = 5700 },
			['9'] = { name = 'Assistant Chief', payment = 5900 },
			['10'] = { name = 'Chief', isboss = true, payment = 6000 },
		},
	},
	sast = {
		label = 'State Trooper',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Cadet', payment = 4000 },
			['1'] = { name = 'Trooper', payment = 4300 },
			['2'] = { name = 'Corporal', payment = 4500 },
			['3'] = { name = 'Sergeant', payment = 4700 },
			['4'] = { name = 'Staff Sergeant', payment = 4900 },
			['5'] = { name = 'Lieutenant', payment = 5100 },
			['6'] = { name = 'Staff Lieutenant', payment = 5300 },
			['7'] = { name = 'Captain', payment = 5500 },
			['8'] = { name = 'Major',isboss = true, payment = 5700 },
			['9'] = { name = 'Lieutenant Colonel',isboss = true, payment = 5900 },
			['10'] = { name = 'Colonel', isboss = true, payment = 6000 },
			['11'] = { name = 'Assistant Commissioner', payment = 7000 },
			['12'] = { name = 'State Commissioner', payment = 8000 },
		},
	},
	bcso = {
		label = 'BCSO',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 4000 },
			['1'] = { name = 'Deputy', payment = 4300 },
			['2'] = { name = 'Corporal', payment = 4500 },
			['3'] = { name = 'Sergeant', payment = 4700 },
			['4'] = { name = 'Lieutenant', payment = 4900 },
			['5'] = { name = 'Captain', payment = 5100 },
			['6'] = { name = 'Major', payment = 5300 },
			['7'] = { name = 'Chief Deputy', payment = 5500 },
			['8'] = { name = 'Assistant Sheriff', payment = 5700 },
			['9'] = { name = 'Under Sheriff', payment = 5900 },
			['10'] = { name = 'Sheriff', isboss = true, payment = 6000 },
		},
	},
	doc = {
		label = 'Department of Corrections',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = true,
		grades = {
			['0'] = { name = 'Recruit', payment = 4000 },
			['1'] = { name = 'Correctional Officer I', payment = 4300 },
			['2'] = { name = 'Correctional Officer II', payment = 4500 },
			['3'] = { name = 'Corporal', payment = 4700 },
			['4'] = { name = 'Sergeant', payment = 4900 },
			['5'] = { name = 'Lieutenant', payment = 5100 },
			['6'] = { name = 'Captain', payment = 5300 },
			['7'] = { name = 'Major', payment = 5500 },
			['8'] = { name = 'Director of Security', payment = 5700 },
			['9'] = { name = 'Deputy Warden', payment = 5900 },
			['10'] = { name = 'Warden', isboss = true, payment = 6000 },
		},
	},
	sasp = {
		label = 'US Marshal',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = true,
		grades = {
			['0'] = { name = 'Deputy U.S. Marshals', payment = 3000 },
			['1'] = { name = 'Supervisory Deputy U.S. Marshals', payment = 4500 },
			['2'] = { name = 'Assistant Chief Deputy U.S. Marshal', payment = 5500 },
			['3'] = { name = 'Chief Deputy U.S. Marshal', isboss = true, payment = 6000 },
		},
	},
	fbi = {
		label = 'Federal Bureau of Investigation',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = true,
		grades = {
			['0'] = { name = 'New agent trainee', payment = 1000 },
			['1'] = { name = 'Field agents', payment = 2000 },
			['2'] = { name = 'Special agent', payment = 3000 },
			['3'] = { name = 'Senior special agent', payment = 4000 },
			['4'] = { name = 'Supervisory special agent', payment = 5000 },
			['5'] = { name = 'Assistant special agent-in-charge', payment = 6000 },
			['6'] = { name = 'Associate deputy director', payment = 7000 },
			['7'] = { name = 'Associate executive assistant director', payment = 8000 },
			['8'] = { name = 'Assistant director', payment = 9000 },
			['9'] = { name = 'Deputy assistant director', payment = 10000 },
			['10'] = { name = 'FBI management', isboss = true, payment = 10000 },
		},
	},
	ambulance = {
		label = 'EMS',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 300 },
			['1'] = { name = 'Paramedic', payment = 500 },
			['2'] = { name = 'Doctor', payment = 1000 },
			['3'] = { name = 'Surgeon', payment = 1500 },
			['4'] = { name = 'Chief', isboss = true, payment = 2000 },
			['5'] = { name = 'Deputy Commissioner', isboss = true, payment = 2500 },
			['6'] = { name = ' Commissioner', isboss = true, payment = 3000 },
		},
	},
	['realestate'] = {
        label = 'Realestate',
        defaultDuty = true,
        grades = {
            ['0'] = {name = 'Rookie', payment = 50 },
            ['1'] = {name = 'Seller', payment = 75 },
            ['2'] = {name = 'Manager', payment = 100 },
            ['3'] = {name = 'Boss', payment = 125, isboss = true, },
        },
    },
	taxi = {
		label = 'Taxi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Driver', payment = 75 },
			['2'] = { name = 'Event Driver', payment = 100 },
			['3'] = { name = 'Sales', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	cardealer = {
		label = 'Vehicle Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Showroom Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Finance', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	mechanic = {
		label = 'Altanic Motorworks',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 750 },
			['1'] = { name = 'Novice', payment = 900 },
			['2'] = { name = 'Experienced', payment = 1000 },
			['3'] = { name = 'Advanced', payment = 1500 },
			['4'] = { name = 'Manager', isboss = true, payment = 2000 },
		},
	},
	redline = {
		label = 'Redline',
		type = 'redline',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 750 },
			['1'] = { name = 'Novice', payment = 900 },
			['2'] = { name = 'Experienced', payment = 1000 },
			['3'] = { name = 'Advanced', payment = 1500 },
			['4'] = { name = 'Manager', isboss = true, payment = 2000 },
		},
	},
	autoexotics = {
		label = 'Auto Exotics',
		type = 'autoexotics',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 750 },
			['1'] = { name = 'Novice', payment = 900 },
			['2'] = { name = 'Experienced', payment = 1000 },
			['3'] = { name = 'Advanced', payment = 1500 },
			['4'] = { name = 'Manager', isboss = true, payment = 2000 },
		},
	},
	harmony = {
		label = 'Harmony',
		type = 'harmony',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 750 },
			['1'] = { name = 'Novice', payment = 900 },
			['2'] = { name = 'Experienced', payment = 1000 },
			['3'] = { name = 'Advanced', payment = 1500 },
			['4'] = { name = 'Manager', isboss = true, payment = 2000 },
		},
	},
	paleto = {
		label = 'Paleto Mechanic',
		type = 'paleto',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 750 },
			['1'] = { name = 'Novice', payment = 900 },
			['2'] = { name = 'Experienced', payment = 1000 },
			['3'] = { name = 'Advanced', payment = 1500 },
			['4'] = { name = 'Manager', isboss = true, payment = 2000 },
		},
	},
	bennys = {
		label = 'bennys',
		type = 'bennys',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 750 },
			['1'] = { name = 'Novice', payment = 900 },
			['2'] = { name = 'Experienced', payment = 1000 },
			['3'] = { name = 'Advanced', payment = 1500 },
			['4'] = { name = 'Manager', isboss = true, payment = 2000 },
		},
	},
	sport = {
		label = 'Sport Mechanic',
		type = 'sport',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 750 },
			['1'] = { name = 'Novice', payment = 900 },
			['2'] = { name = 'Experienced', payment = 1000 },
			['3'] = { name = 'Advanced', payment = 1500 },
			['4'] = { name = 'Manager', isboss = true, payment = 2000 },
		},
	},
	staff = {
		label = 'Afterlyfe RP Staff',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Community Manager', payment = 100 },
			['1'] = { name = 'Admin', payment = 200 },
			['2'] = { name = 'Senior Admin', payment = 300 },
			['3'] = { name = 'Developer', payment = 400 },
			['4'] = { name = 'Co Owner', payment = 500 },
			['5'] = { name = 'Owner', isboss = true, payment = 600 },
		},
	},
	bennys = {
		label = 'Benny\'s Original Motor Works',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	dispatcher = {
		label = 'dispatcher',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Dispatch Cadet', payment = 70 },
			['1'] = { name = 'Operator I', payment = 75 },
			['2'] = { name = 'Operator II', payment = 85 },
			['3'] = { name = 'Senior Operator', payment = 90 },
			['4'] = { name = 'Operations Trainer', payment = 95 },
			['5'] = { name = 'Dispatch Deputy Director', payment = 100 },
			['6'] = { name = 'Dispatch Director', isboss = true, payment = 150 },
		},
	},
	doj = {
		label = 'Law Firm',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Judge Advocate General', payment = 70 },
			['1'] = { name = 'High Court', payment = 75 },
			['2'] = { name = 'High Court Masters', payment = 85 },
			['3'] = { name = 'Circuit Judge', payment = 90 },
			['4'] = { name = 'Recorder', payment = 95 },
			['5'] = { name = 'District Judge', isboss = true, payment = 150 },
		},
	},
	postal = {
        label = 'GoPostal',
        defaultDuty = false,
        offDutyPay = false,
        grades = {
            [0] = { name = 'Delivery Driver', payment = 50 },
            [1] = { name = 'Manager', payment = 150 },
            [2] = { name = 'Boss', isboss = true, payment = 300 },
        }
    },
	['taco'] = {
		label = 'Taco Shop',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
            ['0'] = {name = 'Trainee', payment = 75 },
            ['1'] = {name = 'Employee', payment = 85 },
            ['2'] = {name = 'Cook', payment = 100 },
            ['3'] = {name = 'Manager', payment = 120 },
            ['4'] = {name = 'CEO', isboss = true, payment = 135, },
        },
	},
	['catcafe'] = {
		label = 'Cat Cafe',
		defaultDuty = true,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	['ambulance'] = {
        label = 'EMS',
        type = 'ems',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = {name = 'EMT', payment = 1500 },
            ['1'] = {name = 'EMT Advance', payment = 1500 },
            ['2'] = {name = 'Doctor', payment = 1500 },
            ['3'] = {name = 'Senior Doctor', payment = 1500 },
            ['4'] = {name = 'Surgeon', payment = 1500 },
            ['5'] = {name = 'Medical Advisor', payment = 1500},
            ['6'] = {name = 'Assistant Director',isboss = true, payment = 5000},
            ['7'] = {name = 'Deputy Director',isboss = true, payment = 6000},
            ['8'] = {name = 'Chief Director', payment = 7000, isboss = true },
        },
	},
	['taco'] = {
        label = "Taco",
        defaultDuty = true,
        grades = {
            ['0'] = {name = 'Waiter', payment = 800 },
            ['1'] = {name = 'Delivery Driver', payment = 900 },
            ['2'] = {name = 'Cook', payment = 1000 },
            ['3'] = {name = 'Manager', payment = 1500 },
            ['4'] = {name = 'Owner', payment = 2000, isboss = true},
        },
    },
	['burgershot'] = {
        label = 'Burgershot',
        defaultDuty = true,
        grades = {
            ['0'] = {name = 'Waiter', payment = 800 },
            ['1'] = {name = 'Delivery Driver', payment = 900 },
            ['2'] = {name = 'Cook', payment = 1000 },
            ['3'] = {name = 'Manager', payment = 1500 },
            ['4'] = {name = 'Owner', payment = 2000, isboss = true, },
        },
    },
	["cluckinbell"] = {
        label = "cluckinbell",
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = {name = "Salesman", payment = 500 },
            ['1'] = {name = "Boss", payment = 2000, isboss = true,  },
        },
    },
	['dominos'] = {
        label = "Dominos",
        defaultDuty = true,
        grades = {
            ['0'] = {name = 'Trainee', payment = 800 },
            ['1'] = {name = 'Cashier', payment = 900 },
            ['2'] = {name = 'Crew Lead', payment = 1000 },
            ['3'] = {name = 'Manager', payment = 1500 },
            ['4'] = {name = 'Owner', payment = 2000, isboss = true, },
        },
    },
	['mcdonalds'] = {
        label = "McDonalds",
        defaultDuty = true,
        grades = {
            ['0'] = {name = 'Trainee', payment = 800 },
            ['1'] = {name = 'Cashier', payment = 900 },
            ['2'] = {name = 'Crew Lead', payment = 1000 },
            ['3'] = {name = 'Manager', payment = 1500 },
            ['4'] = {name = 'Owner', payment = 2000, isboss = true, },
        },
    },
	towing = {
		label = 'Towing/Sadot',
		type = 'towing',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 350 },
			['1'] = { name = 'Tow Operator', payment = 500 },
			['2'] = { name = 'Senior Operator', payment = 1000 },
			['3'] = { name = 'Technician', payment = 1500},
			['4'] = { name = 'Senior Technician', isboss = true, payment = 2000 },
		},
	},
}