['ambulance'] = {
        label = 'EMS',
        type = 'ems',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = {name = 'EMT', payment = 20 },
            ['1'] = {name = 'EMT Advance', payment = 40 },
            ['2'] = {name = 'Doctor', payment = 60 },
            ['3'] = {name = 'Senior Doctor', payment = 100 },
            ['4'] = {name = 'Surgeon', payment = 100 },
            ['5'] = {name = 'Medical Advisor', payment = 100},
            ['6'] = {name = 'Assistant Director', payment = 100},
            ['7'] = {name = 'Deputy Director', payment = 100 },
            ['8'] = {name = 'Chief Director', payment = 125, isboss = true },
        },
    },
