QBCore.Functions.CreateUseableItem('spicy_crispy_chicken_sandwich', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('spicy_crispy_chicken_sandwich', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('big_mac', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('big_mac', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('world_famous_fries', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('world_famous_fries', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('chicken_mcnuggets', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('chicken_mcnuggets', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('quarter_pounder', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('quarter_pounder', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('egg_mcmuffin', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('egg_mcmuffin', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('sausage_burrito', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('sausage_burrito', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('double_quarter_pounder', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('double_quarter_pounder', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('big_mac_combo', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('big_mac_combo', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('double_quarter_combo', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('double_quarter_combo', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('mc_combo_chicken', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('mc_combo_chicken', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('egg_cheese_biscuit', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('egg_cheese_biscuit', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('deluxe_crispy_sandwich_combo', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('deluxe_crispy_sandwich_combo', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('spicy_chicken_sandwich_combo', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('spicy_chicken_sandwich_combo', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('mc_nuggets_happy_meal', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('mc_nuggets_happy_meal', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('sausage_biscuit', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('sausage_biscuit', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('hot_fudge_sundae', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('hot_fudge_sundae', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('quarter_pounder_cheese', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('quarter_pounder_cheese', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('spicy_deluxe_sandwich', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('spicy_deluxe_sandwich', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('crispy_chicken_sandwich', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('crispy_chicken_sandwich', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('cheeseburger_combo_meal', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('cheeseburger_combo_meal', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:onEat', source)
end)

QBCore.Functions.CreateUseableItem('mc_flurry_cookies', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('mc_flurry_cookies', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('mc_flurry_candies', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('mc_flurry_candies', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_mcdonalds:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('strawberry_watermelon_slushie', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('strawberry_watermelon_slushie', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_mcdonalds:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('tropical_mango_slushie', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('tropical_mango_slushie', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_mcdonalds:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('mc_coca_cola', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('mc_coca_cola', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_mcdonalds:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('mc_dr_pepper', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('mc_dr_pepper', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_mcdonalds:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('mc_fanta_orange', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('mc_fanta_orange', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_mcdonalds:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('mc_fruit_punch', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('mc_fruit_punch', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_mcdonalds:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('mc_iced_tea', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('mc_iced_tea', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_mcdonalds:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('mc_sprite', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('mc_sprite', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_mcdonalds:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('orange_juice', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('orange_juice', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_mcdonalds:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('mc_cappuccino', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('mc_cappuccino', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_mcdonalds:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('mc_diet_coke', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('mc_diet_coke', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_mcdonalds:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('mc_hot_chocolate', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('mc_hot_chocolate', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_mcdonalds:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('mc_iced_coffee', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('mc_iced_coffee', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_mcdonalds:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('mc_vanilla_shake', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('mc_vanilla_shake', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_mcdonalds:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('mc_strawberry_shake', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('mc_strawberry_shake', 1)
    TriggerClientEvent('ak47_mcdonalds:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_mcdonalds:onDrink', source)
end)

RegisterNetEvent('ak47_mcdonalds:SetMetaData', function(type, amount)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.SetMetaData(type, amount)
    if type == 'hunger' then
        TriggerClientEvent('hud:client:UpdateNeeds', source, amount, xPlayer.PlayerData.metadata.thirst)
    else
        TriggerClientEvent('hud:client:UpdateNeeds', source, xPlayer.PlayerData.metadata.hunger, amount)
    end
end)

