QBCore.Functions.CreateUseableItem('beefy_nacho', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('beefy_nacho', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('chalupa_supreme', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('chalupa_supreme', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('cheese_quesadilla', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('cheese_quesadilla', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('cheesy_black_bean', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('cheesy_black_bean', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('cheesy_gordita_crunch', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('cheesy_gordita_crunch', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('chicken_burrito', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('chicken_burrito', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('churros_dip', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('churros_dip', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('cinnamon_twists', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('cinnamon_twists', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('crunchwrap_supreme', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('crunchwrap_supreme', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('fishtaco', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('fishtaco', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('fries_grande', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('fries_grande', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('quesadilla', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('quesadilla', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('spicy_chicken_burrito', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('spicy_chicken_burrito', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('taco_regular', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('taco_regular', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('tacomeet', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('tacomeet', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('volcano_burrito', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('volcano_burrito', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('crunchytaco', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('crunchytaco', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('soft_taco', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('soft_taco', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('crunchy_taco_supreme', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('crunchy_taco_supreme', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('soft_taco_supreme', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('soft_taco_supreme', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('crispy_chicken_staco', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('crispy_chicken_staco', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('t_diet_pepsi', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('t_diet_pepsi', 1)
    TriggerClientEvent('ak47_taco:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_taco:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('t_pepsi_max', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('t_pepsi_max', 1)
    TriggerClientEvent('ak47_taco:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_taco:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('t_seven_up', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('t_seven_up', 1)
    TriggerClientEvent('ak47_taco:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_taco:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('t_tango_apple', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('t_tango_apple', 1)
    TriggerClientEvent('ak47_taco:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_taco:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('t_tango_orange', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('t_tango_orange', 1)
    TriggerClientEvent('ak47_taco:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_taco:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('crunchwrap_supreme_meal', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('crunchwrap_supreme_meal', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_taco:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('quesadilla_cravings', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('quesadilla_cravings', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_taco:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('two_taco_supreme', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('two_taco_supreme', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_taco:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

QBCore.Functions.CreateUseableItem('volcano_burrito_meal', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('volcano_burrito_meal', 1)
    TriggerClientEvent('ak47_taco:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_taco:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_taco:onEat', source)
end)

RegisterNetEvent('ak47_taco:SetMetaData', function(type, amount)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.SetMetaData(type, amount)
    if type == 'hunger' then
        TriggerClientEvent('hud:client:UpdateNeeds', source, amount, xPlayer.PlayerData.metadata.thirst)
    else
        TriggerClientEvent('hud:client:UpdateNeeds', source, xPlayer.PlayerData.metadata.hunger, amount)
    end
end)

