QBCore.Functions.CreateUseableItem('extra_vagan_zza', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('extra_vagan_zza', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('meat_zza', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('meat_zza', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('philly_cheese_steak', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('philly_cheese_steak', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('pacific_veggie', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('pacific_veggie', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('honolulu_hawaiian', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('honolulu_hawaiian', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('pizza_deluxe', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('pizza_deluxe', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('cali_chicken_bacon', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('cali_chicken_bacon', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('buffalo_chicken', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('buffalo_chicken', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('ultimate_pepperoni', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('ultimate_pepperoni', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('memphis_bbq_chicken', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('memphis_bbq_chicken', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('wisconsin_cheese', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('wisconsin_cheese', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('spinach_feta', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('spinach_feta', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('chicken_habanero', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('chicken_habanero', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('mediterranean_veggie', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('mediterranean_veggie', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('philly_cheese_sandwich', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('philly_cheese_sandwich', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('chicken_bacon_ranch', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('chicken_bacon_ranch', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('italian_sandwich', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('italian_sandwich', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('p_chicken_alfredo', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('p_chicken_alfredo', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('italian_sausage_marinara', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('italian_sausage_marinara', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('chicken_carbonara', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('chicken_carbonara', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('pasta_primavera', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('pasta_primavera', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_dominos:onEat', source)
end)

QBCore.Functions.CreateUseableItem('d_coca_cola', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('d_coca_cola', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_dominos:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('d_dr_pepper', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('d_dr_pepper', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_dominos:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('d_fanta_orange', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('d_fanta_orange', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_dominos:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('d_fruit_punch', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('d_fruit_punch', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_dominos:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('d_sprite', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('d_sprite', 1)
    TriggerClientEvent('ak47_dominos:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_dominos:onDrink', source)
end)

RegisterNetEvent('ak47_dominos:SetMetaData', function(type, amount)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.SetMetaData(type, amount)
    if type == 'hunger' then
        TriggerClientEvent('hud:client:UpdateNeeds', source, amount, xPlayer.PlayerData.metadata.thirst)
    else
        TriggerClientEvent('hud:client:UpdateNeeds', source, xPlayer.PlayerData.metadata.hunger, amount)
    end
end)

