QBCore.Functions.CreateUseableItem('family_bundle_classic', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('family_bundle_classic', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 80)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('croissanwich_meal', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('croissanwich_meal', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 50)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('loaded_croissanwich_meal', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('loaded_croissanwich_meal', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('sausage_croissanwich', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('sausage_croissanwich', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 50)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('ham_egg_cheese', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('ham_egg_cheese', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 40)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('double_sausage_croissanwich', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('double_sausage_croissanwich', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('bacon_ham_sausage', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bacon_ham_sausage', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 50)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('double_sausage_biscuit', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('double_sausage_biscuit', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('buttermilk_biscuit', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('buttermilk_biscuit', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 50)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('egg_normous_burrito', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('egg_normous_burrito', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('pancake_sausage_platter', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('pancake_sausage_platter', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 70)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('small_hash_browns', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('small_hash_browns', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 50)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('french_toast_sticks', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('french_toast_sticks', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 40)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('whopper_with_cheese', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('whopper_with_cheese', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('bacon_king', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bacon_king', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 50)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('double_cheeseburger', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('double_cheeseburger', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 70)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('bacon_double_cheeseburger', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bacon_double_cheeseburger', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('rodeo_burger', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('rodeo_burger', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 50)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('bs_hamburger', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bs_hamburger', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 40)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('texas_double_whopper', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('texas_double_whopper', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('original_chicken_sandwich', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('original_chicken_sandwich', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 50)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('deluxe_chicken_sandwich', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('deluxe_chicken_sandwich', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 70)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('spicy_deluxe_sandwich', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('spicy_deluxe_sandwich', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 50)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('chicken_fries', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('chicken_fries', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 40)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('chicken_nuggets', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('chicken_nuggets', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('big_fish', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('big_fish', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 50)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('bs_chicken_jr', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bs_chicken_jr', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 40)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('small_classic_fries', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('small_classic_fries', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 50)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('small_onion_rings', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('small_onion_rings', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 40)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('bs_mozzarella_sticks', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bs_mozzarella_sticks', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 50)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('jalapeno_cheddar_bites', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('jalapeno_cheddar_bites', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('cheesy_tots', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('cheesy_tots', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 50)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('sundae_pie', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('sundae_pie', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 40)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('soft_serve_cone', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('soft_serve_cone', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 50)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('soft_serve_cup', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('soft_serve_cup', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 40)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('cookie_shake', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('cookie_shake', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('chocolate_cookie_shake', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('chocolate_cookie_shake', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 60)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('chocolate_shake', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('chocolate_shake', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('vanilla_shake', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('vanilla_shake', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 60)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('strawberry_shake', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('strawberry_shake', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('bs_coca_cola', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bs_coca_cola', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('bs_diet_coke', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bs_diet_coke', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('bs_iced_tea', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bs_iced_tea', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('bs_sprite', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bs_sprite', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('bs_sprite_zero', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bs_sprite_zero', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('bs_barqs_beer', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bs_barqs_beer', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 60)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('barqs_diet_beer', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('barqs_diet_beer', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('bs_dr_pepper', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bs_dr_pepper', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('bs_fanta_orange', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bs_fanta_orange', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('bs_yello_mello', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bs_yello_mello', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 60)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('bs_fruit_punch', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bs_fruit_punch', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('pink_lemonade', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('pink_lemonade', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 60)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('sun_apple_juice', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('sun_apple_juice', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('bs_cafe_decaf', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bs_cafe_decaf', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('plain_iced_coffee', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('plain_iced_coffee', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 60)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('bs_orange_juice', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bs_orange_juice', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('bottle_diet_coke', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('bottle_diet_coke', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'thirst', 40)
    TriggerClientEvent('ak47_burgershot:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('cheeseburger_king_jr', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('cheeseburger_king_jr', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 70)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('nuggets_king_jr', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('nuggets_king_jr', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

QBCore.Functions.CreateUseableItem('hamburger_king_jr', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('hamburger_king_jr', 1)
    TriggerClientEvent('ak47_burgershot:add', source, 'hunger', 70)
    TriggerClientEvent('ak47_burgershot:onEat', source)
end)

RegisterNetEvent('ak47_burgershot:SetMetaData', function(type, amount)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.SetMetaData(type, amount)
    if type == 'hunger' then
        TriggerClientEvent('hud:client:UpdateNeeds', source, amount, xPlayer.PlayerData.metadata.thirst)
    else
        TriggerClientEvent('hud:client:UpdateNeeds', source, xPlayer.PlayerData.metadata.hunger, amount)
    end
end)